@ConferencesAPI_HostAddress = https://localhost:7099
@token = CfDJ8H6f0PVOH8VHooLBybin6seL35jZWYCobF3LqkPsmGXx2vZk7Oc4QfUr83wDfg0ec6Tji3xIgiGxUm8vvdoVr39nkdoGtUS41yguQBsVNW905_-7wIVRrAtV-2DxkXYdJ5vnMhclkQrC-fPIgAJeKTfpM8VS-8RHkiE07XCTl2ppNz3wj63jc5CKL_sQgwifzZpFIZY02BBVdFL3k2l3HPxxCLax5Ue5pRJRU2GPKNyLgliAVW0dIElk6ArfPnJE-jLI8ehAp0PNYSzM_nNCfjdu9ut5YM_VO2yPyCx0gebkLAB-mbB250SkCKqoqCHbzMg2uU66PufYhRirMpnjE71GBHZHq0RropPXPP8kStPD4LRYAfqxYpaZbYbN6-WKTwRgZFMkJQnTCQoKYBtJQjigXsQL6lBwQlbja3FPn8LtpNSLTT8q4vytKHeTZelipjccacoE1lJeVS4eljDzO0Qh5pYHL42sjJ7GyIEsPUU64EJc23Z4EXngWX-SD8zkTtezaj-Z3SFj5PMLSswbCGqErs40O_vdRIujeFenLlcOZuu7an7dUUeSj6gEAClucq21OSA04dBBve2eDPcZXI34LXqqCbKEN4ItK6wpVBZZapRFWV06uMnUxi8EKN6GfBf-Xoi7KpKSpRLYK8m_y-0ccBO8B9vepc81_ugWTUejldPV2NhT_-8KBWEk5yz_jg


GET {{ConferencesAPI_HostAddress}}/api/conferences?searchPhrase=conf&pageSize=5&pageNumber=1&sortBy=CategoryName&SortDirection=Desc
Accept: application/json

###

GET {{ConferencesAPI_HostAddress}}/api/conferences/5
Accept: application/json

###

POST {{ConferencesAPI_HostAddress}}/api/conferences
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Test Conference Title444",
  "description": "The best conference in the world",
  "logoUrl": "https://placehold.co/600x400",
  "startDate": "2024-06-14T11:00:00",
  "endDate": "2024-06-16T17:00:00",
  "location": {
    "latitude": 20,
    "longitude": 20
  },
  "websiteUrl": "https://www.google.com/",
  "categoryId": 8
}

###

DELETE {{ConferencesAPI_HostAddress}}/api/conferences/16
Authorization: Bearer {{token}}

###

PATCH {{ConferencesAPI_HostAddress}}/api/conferences/17
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "New title",
  "location": {
    "longitude": -18
  }
}

###

POST {{ConferencesAPI_HostAddress}}/api/conferences/5/important-dates
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Send abstract",
  "date": "2024-06-10T14:00:00"
}

###

GET {{ConferencesAPI_HostAddress}}/api/conferences/5/important-dates

###

GET {{ConferencesAPI_HostAddress}}/api/conferences/5/important-dates/7

###

DELETE {{ConferencesAPI_HostAddress}}/api/conferences/5/important-dates/7
Authorization: Bearer {{token}}

###

POST {{ConferencesAPI_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "test@interia.pl",
  "password": "Password1!"
}

###

POST {{ConferencesAPI_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "test@interia.pl",
  "password": "Password1!"
}

###